---
- name: "updating the packages"
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes


- name: "Configuring wordpress on ubuntu"
  apt:
    name:
      - apache2
      - php
      - php-mysql
    state: present
  notify:
    - restart-apache2  

- name: "Creating Document root"
  file:
    path: "/var/www/html/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
  notify:
    - restart-apache2

- name: "setting up apache.conf file"
  template:
    src: "apache.conf.new"
    dest: "/etc/apache2/sites-enabled/{{ http_conf }}"
  notify:
    - restart-apache2
    

- name: "changing the port"
  template:
    src: "ports.new.conf"
    dest: "/etc/apache2/ports.conf"
  notify:
    - restart-apache2  

- name: "mariadb installation"
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
    state: present

- name: "mariadb restart/enable"
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: " resetting pass for maria db root"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_password: ""
    name: "root"
    password: "{{ mariadb_root }}"
    host_all: true

- name: "mariadb removing anonymous user"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: ""
    state: absent
    host_all: true

- name: "Creating wordpress db"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: "{{ mariadb_database }}"
    state: present

- name: "Creating wordpress user"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root }}"
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    state: present
    priv: "{{ mariadb_database }}.*:ALL"

# tasks file for lamp
